### ISSUE TITLE
Wimdows 7

### ISSUE THREAD

**Issue by harryray33** [ChristianGalla/AutoStartConfirm#19]
Will this run under Windows 7?

Thanks

**Comment by ChristianGalla** [comment]
Unfortunately, this program doesn't run on Windows 7.

A core element are the toast notifications that were introduced in Windows 8 and extended by new features on Windows 10.

Also, Windows 7 support ended January 2020. I am not planning to add support for operating systems that are not supported by Microsoft anymore.
